{% set version = "0.5.4" %}

package:
  name: sphinx-mdinclude
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx_mdinclude/sphinx_mdinclude-{{ version }}.tar.gz
  sha256: 4a58c8f02e95a2b7ba0eb77a851e096e42c66958f9f7ffe575e427cf659e1789

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - flit-core
    - mistune >=2.0,<3.0
    - docutils >=0.16,<1.0
    - pygments >=2.8
  run:
    - python >=3.8
    - mistune >=2.0,<3.0
    - docutils >=0.16,<1.0
    - pygments >=2.8

test:
  requires:
    - pip
  imports:
    - sphinx_mdinclude
  commands:
    - pip check

about:
  home: https://github.com/omnilib/sphinx-mdinclude
  summary: Sphinx extension for including or writing pages in Markdown format.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://sphinx-mdinclude.readthedocs.io
  dev_url: https://github.com/omnilib/sphinx-mdinclude

extra:
  recipe-maintainers:
    - hmaarrfk
    - tdegeus
